# Generated by Django 3.2.8 on 2021-11-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_mailregisterforinfomation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRegisterForInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mail_register_for_infomation',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MailRegisterForInfomation',
        ),
    ]
